import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./component/Nav";



const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} w-screen h-screen bg-black`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
